install.packages("ggplot2")
install.packages("GGally")
install.packages("ggrepel")
install.packages("directlabels")
install.packages("corrplot")
install.packages("bio3d")
install.packages("RColorBrewer")
install.packages("dplyr")
install.packages("ggthemes")
install.packages("grid")
install.packages("gridBase")
install.packages("gridExtra")
install.packages("scales")
install.packages("png")
install.packages("igraph")
install.packages("pracma")
install.packages("formattable")
install.packages("pander")
install.packages("knitr")
install.packages("rmarkdown")
install.packages("ggedit")
install.packages("plot3D")
install.packages("tidyr")
install.packages("network")
install.packages("ggraph")
install.packages("visNetwork")
install.packages("networkD3")
install.packages("psych")
install.packages("Peptides")
if(!require(devtools)) install.packages("devtools")
  devtools::install_github("kassambara/ggpubr")
install.packages("igraph") 
install.packages("network") 
install.packages("sna")
install.packages("ggraph")
install.packages("visNetwork")
install.packages("threejs")
install.packages("networkD3")
install.packages("ndtv")
install.packages("reshape2")
install.packages("ggdag")
install.packages("devtools")
install.packages("mindr")
install.packages("xml2")
install.packages("striprtf")
install.packages("plotly")
install.packages("zoo")
install.packages("ggside")
install.packages("ggExtra")
citation("devtools")

library(ggExtra) 
library(zoo)
library(formattable)
library(plotly) 
library(mindr)
library(striprtf)
library(devtools) 
library(reshape2) 
library(ggplot2) 
library(GGally) 
library(sna)
library(ggrepel) 
library(directlabels)
library(corrplot) 
library(bio3d) 
library(RColorBrewer) 
library(dplyr) 
library(ggthemes) 
library(grid) 
library(gridBase) 
library(gridExtra) 
library(scales)
library(png) 
library(igraph)
library(pracma)
library(formattable)
library(pander)
library(knitr)
library(rmarkdown) 
library(Peptides) 
library(ggedit)
library(plot3D)
library(tidyr)
library(plyr)
library(ggnetwork)
library(network)
library(ggraph)
library(visNetwork)
library(networkD3)
library(psych)
library(ggpubr)
library(xml2)
library(ggside) 

install.packages("unix") 
library(unix)
rlimit_as(1e12) 
  
###cuadro de colores de ggplot2
d=data.frame(c=colors(), y=seq(0, length(colors())-1)%%66, x=seq(0, length(colors())-1)%/%66)
ggplot() +
  scale_x_continuous(name="", breaks=NULL, expand=c(0, 0)) +
  scale_y_continuous(name="", breaks=NULL, expand=c(0, 0)) +
  scale_fill_identity() +
  geom_rect(data=d, mapping=aes(xmin=x, xmax=x+1, ymin=y, ymax=y+1), fill="white") +
  geom_rect(data=d, mapping=aes(xmin=x+0.05, xmax=x+0.95, ymin=y+0.5, ymax=y+1, fill=c)) +
  geom_text(data=d, mapping=aes(x=x+0.5, y=y+0.5, label=c), colour="black", hjust=0.5, vjust=1, size=3)

plots  <- list(A,B,C)
do.call(grid.arrange, plots)
grid.arrange(A,B,C, ncol=3, nrow=1)

display.brewer.all()

library(knitr)
library(rmarkdown)

rmarkdown::render("update.Rmd")

  ggarrange(C3S, D3S,  labels = c("C", "D"),
          common.legend = TRUE, legend = "bottom") 
  